### ISSUE TITLE
How to set a new width for the splitRow?

### ISSUE THREAD

**Issue by alonreptor** [EurekaCommunity/SplitRow#11]
![image](https://user-images.githubusercontent.com/20382575/37468682-55120a56-286c-11e8-8c29-3edf360b6a98.png)

Hi, 
Im trying to move the split line so that the selected value will have more space when  it is displayed...
please advise

**Comment by marbetschar** [comment]
@alonreptor please have a look at the `rowLeftPercentage` of the `SplitRow` and set it to the desired value. Here's an example:

```
SplitRow<PushRow<String>,DecimalRow>{
    $0.rowLeftPercentage = 0.7
}
```

**Comment by alonreptor** [comment]
Thank!
