### ISSUE TITLE
Right and left margins of SplitRow

### ISSUE THREAD

**Issue by sverin** [EurekaCommunity/SplitRow#27]
The SplitRow does not align with other rows from Eureka. Both left and right sides are closer to the edges than the normal TextRow. It's not much but a couple of pixels on both sides.

![image](https://user-images.githubusercontent.com/2380634/47587888-a3a11500-d964-11e8-9b41-26b1a75ff9a8.png)

Otherwise a great addition to Eureka

**Comment by zunjae** [comment]
A workaround for the left margin is to add a leading space at the title, so:
