### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by hungeric** [EurekaCommunity/SplitRow#29]
Instead of using Cocoapod, can we support Carthage?

**Comment by marbetschar** [comment]
@hungeric `SplitRow` supports Cocoapods as well as Carthage. Just put the following into your Cartfile and your ready to go:

```
github "EurekaCommunity/SplitRow" ~> 1.2.1
```

**Comment by hungeric** [comment]
@marbetschar Thanks, it wasn't in the .readme so I thought it only supported pods.
Quick question, was there a reason why you used a tableview instead of just use a single view with 2 sections?

**Comment by marbetschar** [comment]
@hungeric the table view is used because of the way Eureka works internally. It’s Cell functionalities are tightly coupled to a UITableViewCell. Therefore I found it to be best to stick to what’s there in favour of an easy implementation. That’s why I used TableView.

**Comment by hungeric** [comment]
@marbetschar thank you for your response.  I was just curious, i see your point now.  this is a great extension to Eureka, I appreciate and applaud for your effort in this.
