### ISSUE TITLE
Make extension compatible with Eureka 5.0.0

### ISSUE THREAD

**Issue by mtnbarreto** [EurekaCommunity/SplitRow#34]
@marbetschar Do you have some time to upgrade it?

**Comment by marbetschar** [comment]
@mtnbarreto: yes, thanks to @kramerc this is already in the works: #33

**Comment by kramerc** [comment]
@marbetschar: @kamerc you mean

**Comment by kamerc** [comment]
This is now complete. Version 2.0.0 is available.
