### ISSUE TITLE
Posibility to hide left/right row

### ISSUE THREAD

**Issue by dneykov** [EurekaCommunity/SplitRow#49]
Hello,

I'm trying to hide only the right row but is not working. Is that possible with SplitRow?

Thanks

**Comment by marbetschar** [comment]
Hi @dneykov!

This is not possible with SplitRow - however, you can swap the entire row using Eureka's builtin `hidden` flag:

https://github.com/xmartlabs/Eureka#dynamically-hide-and-show-rows-or-sections--

**Comment by dneykov** [comment]
@marbetschar Thanks for the quick response.
I will try your suggestion.
