### ISSUE TITLE
[SPM] Please tag a release including Package.swift file

### ISSUE THREAD

**Issue by Dean151** [EurekaCommunity/SplitRow#50]
SPM support have been merged in main branch.
But no release tag were created since then.
Please to fully support SPM, tag a new release

**Comment by marbetschar** [comment]
Done. However, since I do not have access to the Hardware anymore I'm unable to release to Cocoapods. Maybe @kamerc can help out.

**Comment by kamerc** [comment]
@Dean151 I just pushed an update for the cocoapod spec file to be set to release 2.2.0
