### ISSUE TITLE
Add versioning scheme

### ISSUE THREAD

**Issue by enquora** [EurekaCommunity/SplitRow#7]
Tag commits intended as separate releases.

**Comment by marbetschar** [comment]
Waiting for the pull request to get merged into the official Eureka, in order to set the dependency to it before tagging any release:

https://github.com/xmartlabs/Eureka/pull/1338

**Comment by marbetschar** [comment]
The change is now implemented in [Eureka/master](https://github.com/xmartlabs/Eureka/blob/master/Source/Core/BaseRow.swift). Still waiting for a new Eureka release to add versioning scheme.

**Comment by marbetschar** [comment]
https://github.com/xmartlabs/Eureka/issues/1443

**Comment by marbetschar** [comment]
Created initial release `1.0.0` which depends upon Eureka `4.1.0`.
