### ISSUE TITLE
sigbart error

### ISSUE THREAD

**Issue by hfzwhd** [EurekaCommunity/SplitRow#9]
me got error like below when running an example. i'm new to this. help pls.

> dyld: Library not loaded: @rpath/SplitRow.framework/SplitRow
  Referenced from: /var/containers/Bundle/Application/5F0927C0-7C88-4336-9A31-AB212DD86158/Example.app/Example
  Reason: image not found

**Comment by marbetschar** [comment]
@hfzwhd looks like the SplitRow framework is not copied to your app, and therefore the `Library not loaded` and `Reason: image not found` errors are thrown.

Please make sure you add the Custom Build Phase for Carthage which executes the following command:

`/usr/local/bin/carthage copy-frameworks`

For more details, please see the [README of Carthage](https://github.com/Carthage/Carthage).

Feel free to reopen this issue, if it still persists.
